export const TOKEN = 'TOKEN' // 登录
export const USER_INFO = 'USER_INFO' // 用户信息
export const SYS_INFO = 'SYS_INFO'
export const LOGIN_STATUS = 'LOGIN_STATUS' // 登录状态
export const FRIENDS_INFO = 'FRIENDS_INFO'
export const GROUP_INFO = 'GROUP_INFO'
export const CONVERSATIONS_LIST = 'CONVERSATIONS_LIST'
export const ONLINE_USER = 'ONLINE_USER'
export const UNREAD = 'UNREAD'
export const SYS_NEWS_LIST = 'SYS_NEWS_LIST'
export const FRIENDS_LIST = 'FRIENDS_LIST'
export const GROUPS_LIST = 'GROUPS_LIST'
export const ALL_CHAT_LIST = 'ALL_CHAT_LIST'
